### ISSUE TITLE
Errors with FM

### ISSUE THREAD

**Issue by ProgrammerDan** [Civcraft/FactoryMod#168]
[14:38:29 ERROR]: Error occurred while enabling FactoryMod v2.0.0 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.LinkedList.checkElementIndex(LinkedList.java:553) ~[?:1.7.0_79]
        at java.util.LinkedList.get(LinkedList.java:474) ~[?:1.7.0_79]
        at com.github.igotyou.FactoryMod.ConfigParser.parse(ConfigParser.java:80) ~[?:?]
        at com.github.igotyou.FactoryMod.FactoryMod.onEnable(FactoryMod.java:28) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-5f38d38-efd6c
b0]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-
5f38d38-efd6cb0]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot
-5f38d38-efd6cb0]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-5f38
d38-efd6cb0]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-5
f38d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-5f38d38
-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-5f38d38
-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-5f38d38
-efd6cb0]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-5f38
d38-efd6cb0]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-5f38d
38-efd6cb0]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

On Startup, both with default config and a full config.

**Comment by Maxopoly** [comment]
This means I forgot to document a value in the default config. I saw you already added some more logging to the parsing, did you find out what was missing?

**Comment by ProgrammerDan** [comment]
Yep, turns out default fuel has no default fuel hardcoded, so you must specify one.

There's another weird error I can't track down -- the time converter is reporting an invalid time of 7d, but "7d" literally doesn't exist as a declaration in the config, nor in either FM or CivModeCore projects... weird.

**Comment by ProgrammerDan** [comment]
Fixed here https://github.com/Civcraft/FactoryMod/commit/8c69355c6a5bc230cc6411324eac07905325b849

just gracefully errors instead of NPE

**Comment by Maxopoly** [comment]
Yeah, when I was working on it I would just check the line where it threw the NPE to find out what I forgot to specify, but this makes config debugging a lot easier. Is the 7d thing still happening?

**Comment by ProgrammerDan** [comment]
Yeah it is. I had no luck tracking it down and it doesn't seem to actively hurt anything yet ... so... dunno.

**Comment by ProgrammerDan** [comment]
Example:

[01:20:40 INFO]: [FactoryMod] Enabling FactoryMod v2.0.2
[01:20:40 INFO]: [FactoryMod] Main Plugin Events and Config Command registered
[01:20:40 ERROR]: Invalid time value in config:7d
[01:20:40 INFO]: ItemStack{DIRT x 64};ItemStack{STONE x 64};
[01:20:40 INFO]: [FactoryMod] Parsed factory Workshop

**Comment by Maxopoly** [comment]
That item stack message means I forgot to remove a debug message. I'll take a look at the 7d error later, I remember encountering the same error when I tested it, but I forgot what caused it or how I fixed it.

**Comment by ProgrammerDan** [comment]
Yeah, that debug message is OK-ish for now. :D
